name: recipe_book

volumes:
  sql-server-data:
    driver: local

services:
  recipebook:
    image: ${DOCKER_REGISTRY-}recipebook
    container_name: app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: RecipeBook/Dockerfile
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server
    container_name: database
    env_file:
      - RecipeBook/sqlserver.env
    restart: always
    volumes:
      - sql-server-data:/var/opt/mssql/
      - /c/docker/shared:/usr/shared
    ports:
      - '1433:1433'
